### ISSUE TITLE
FASTA sequence name contains too much information

### ISSUE THREAD

**Issue by andrewyatz** [tonyyzy/GC_analysis#3]
Currently the tests report sequence identifiers such as `>ENA|A00145|A00145.1 B.taurus BoIFN-alpha A mRNA ` where is should be `ENA|A00145|A00145.1`. 

When reading on line https://github.com/tonyyzy/GC_analysis/blob/master/scripts/GC_analysis.py#L50 you should split that line on whitespace using a regular expression e.g. `\s+` and take the first element from the resulting list

**Comment by tonyyzy** [comment]
This has been done. I vaguely remembered you mentioned just `A00145.1` is better than `ENA|A00145|A00145.1`?

**Comment by andrewyatz** [comment]
Yes but that’s up to the input fasts record to be formatted as such. We may
have to do this in our pipeline but the go binary shouldn’t be concerned
with identifier formatting
