### ISSUE TITLE
BigWig can not store data with overlapping windows

### ISSUE THREAD

**Issue by tonyyzy** [tonyyzy/GC_analysis#9]
@leannehaggerty @andrewyatz
Hi,
I am working on incorporating pyBigWig to write to BigWig files directly from my GC program. It seems like BigWig doesn't like files with overlapping items. For example, if I conduct a GC analysis with window size 5 and shift 3, the BigWig library would give me an error saying there are overlapping items.
I tried to use UCSC's wigToBigWig binary to do the conversion on the wiggle file generated with the same setting, and it gave me the same warning.
I think I will add a testing at the beginning of my program, if the window size is larger than shift and the output format is chosen to be BigWig then an error/warning will be displayed.

Any thoughts?

**Comment by leannehaggerty** [comment]
Hi Tony

Sorry, should've have seen this coming. Yes, as you've seen, bigWig files don't like overlapping data values. 

Wiggle files with overlap can be loaded in to the browser, the spans will be truncated and each new region will start 3 bp (your shift size) from the start of the previous region. For bigwig, however, one datapoint creates one bar graph that covers 5 bp (your window size).

I think your solution to check that window_size >= shift_size is a good one. You should probably include a message to the user, something like "The input window/shift sizes will result in overlapping data points in the output wiggle file, this cannot be converted to bigwig, do you wish to create the wig file anyway?"... or whatever you think is best.
